import { Header } from "@/components/header/Header";
import { NavigationMobile } from "@/components/navigation/NavigationMobile";
// import { NavigationList } from "@/components/navigation/NavigationList";
// import { moksData } from "@/data/moks";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="drawer drawer-end min-h-svh">
          <input id="my-drawer-2" type="checkbox" className="drawer-toggle" />
          <div className="drawer-content flex flex-col h-full min-h-screen">
            {/* Navbar and PC menu */}
            <Header />
            <main>
              {/* Page content here */}
              {children}
            </main>
          </div>
          {/* there is mobile menu logic  */}
          <NavigationMobile />
        </div>
      </body>
    </html>
  );
}
