import { Header } from "@/components/header/Header";
import { NavigationMobile } from "@/components/navigation/NavigationMobile";
import { Footer } from "@/components/footer/Footer";
import { Fira_Sans, Kurale } from "next/font/google";
import { Modal } from "@/components/UI/Modal";
import "./globals.css";

const firaSans = Fira_Sans({
  variable: "--font-fira-sans",
  subsets: ["cyrillic", "latin"],
  weight: ["300", "400"],
  display: "swap",
});

const kurale = Kurale({
  variable: "--font-kurale",
  subsets: ["cyrillic", "latin"],
  weight: ["400"],
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="uk">
      <body
        className={`${firaSans.variable} ${kurale.variable} ${firaSans.className} antialiased`}
      >
        <div className="drawer drawer-end min-h-svh">
          <input id="my-drawer-2" type="checkbox" className="drawer-toggle" />
          <div className="drawer-content flex flex-col h-full min-h-screen">
            {/* Navbar and PC menu */}
            <Header />
            <main className="pt-15">
              {/* Page content here */}
              {children}
            </main>
            <Footer />
            <Modal />
          </div>
          {/* there is mobile menu logic  */}
          <NavigationMobile />
        </div>
      </body>
    </html>
  );
}
